Scene: testing.zsc
ActiveCameraUUID: 5139909329933187455
Entities:
  - Entity: 12237881735723462603
    TagComponent:
      Tag: Left Wall
    TransformComponent:
      Translation: [-10, 0, 0]
      EulerAngles: [0, 0, 0]
      Scale: [0.5, 20, 1]
    RigidBody2DComponent:
      Type: Static
      FixedRotation: false
    RectColliderComponent:
      Offset: [0, 0]
      HalfExtent: [0.5, 0.5]
      Density: 1
      Friction: 0.5
      Restitution: 0.5
      RestitutionThreshold: 0.5
  - Entity: 17506434985116989594
    TagComponent:
      Tag: Right Wall
    TransformComponent:
      Translation: [10, 0, 0]
      EulerAngles: [0, 0, 0]
      Scale: [0.5, 20, 1]
    RigidBody2DComponent:
      Type: Static
      FixedRotation: false
    RectColliderComponent:
      Offset: [0, 0]
      HalfExtent: [0.5, 0.5]
      Density: 1
      Friction: 0.5
      Restitution: 0.5
      RestitutionThreshold: 0.5
  - Entity: 14741283407467247787
    TagComponent:
      Tag: Top Wall
    TransformComponent:
      Translation: [0, 10, 0]
      EulerAngles: [0, 0, 0]
      Scale: [20, 0.5, 1]
    RigidBody2DComponent:
      Type: Static
      FixedRotation: false
    RectColliderComponent:
      Offset: [0, 0]
      HalfExtent: [0.5, 0.5]
      Density: 1
      Friction: 0.5
      Restitution: 0.5
      RestitutionThreshold: 0.5
  - Entity: 5139909329933187455
    TagComponent:
      Tag: Camera
    TransformComponent:
      Translation: [0, 0, 0]
      EulerAngles: [0, 0, 0]
      Scale: [1, 1, 1]
    CameraComponent:
      Camera:
        ProjectionType: Orthographic
        OrthographicSize: 20
        OrthographicNearClip: -1
        OrthographicFarClip: 1
        PerspectiveFOV: 1.04719758
        PerspectiveNearClip: 0.00999999978
        PerspectiveFarClip: 1000
      FixedAspectRatio: false
  - Entity: 15271923336665084770
    TagComponent:
      Tag: Top Wall
    TransformComponent:
      Translation: [0, -10, 0]
      EulerAngles: [0, 0, 0]
      Scale: [20, 0.5, 1]
    RigidBody2DComponent:
      Type: Static
      FixedRotation: false
    RectColliderComponent:
      Offset: [0, 0]
      HalfExtent: [0.5, 0.5]
      Density: 1
      Friction: 0.5
      Restitution: 0.5
      RestitutionThreshold: 0.5
  - Entity: 3242436916581331946
    TagComponent:
      Tag: Player
    TransformComponent:
      Translation: [0, 0, 0]
      EulerAngles: [0, -0, 0]
      Scale: [0.699999988, 0.699999988, 1]
    SpriteComponent:
      Tint: [0.22897689, 0.926640928, 0.902397633, 1]
      TextureTiling: 1
      Animated: false
    ScriptComponent:
      ScriptName: Bud.Examples.Player
      FieldValues:
        InputStrength: 20
        Drag: 0.00999999978
        IgnoreGravity: true
        WASD: true
    RigidBody2DComponent:
      Type: Dynamic
      FixedRotation: false
    RectColliderComponent:
      Offset: [0, 0]
      HalfExtent: [0.5, 0.5]
      Density: 1
      Friction: 0
      Restitution: 1
      RestitutionThreshold: 0