Scene: physics_test.zsc
Entities:
  - Entity: 23152837592538
    TagComponent:
      Tag: Camera
    TransformComponent:
      Translation: [0, 0, 9.5]
      EulerAngles: [0, 0, 0]
      Scale: [1, 1, 1]
    CameraComponent:
      Camera:
        ProjectionType: Perspective
        OrthographicSize: 10
        OrthographicNearClip: -1
        OrthographicFarClip: 1
        PerspectiveFOV: 1.04719758
        PerspectiveNearClip: 0.00999999978
        PerspectiveFarClip: 1000
      Active: true
      FixedAspectRatio: false
  - Entity: 23152837592538
    TagComponent:
      Tag: Platform
    TransformComponent:
      Translation: [0.0596504211, -4.9547286, 0]
      EulerAngles: [0, -0, 0]
      Scale: [16.1499996, 0.25, 1]
    SpriteComponent:
      Tint: [0.339221537, 0.455598474, 0.253305703, 1]
    RigidBody2DComponent:
      Type: Static
      FixedRotation: false
    RectColliderComponent:
      Offset: [0, 0]
      HalfExtent: [0.5, 0.5]
      Density: 1
      Friction: 0.5
      Restitution: 0.5
      RestitutionThreshold: 0.5
  - Entity: 23152837592538
    TagComponent:
      Tag: Box1
    TransformComponent:
      Translation: [-0.233143926, 5.61061716, 0]
      EulerAngles: [0, -0, 0.785572648]
      Scale: [0.999981999, 0.999981999, 1]
    SpriteComponent:
      Tint: [0.99227798, 0.743250728, 0.283507973, 1]
    RigidBody2DComponent:
      Type: Dynamic
      FixedRotation: false
    RectColliderComponent:
      Offset: [0, 0]
      HalfExtent: [0.5, 0.5]
      Density: 1
      Friction: 0.5
      Restitution: 0.5
      RestitutionThreshold: 0.5