Scene: test4.zsc
Entities:
  - Entity: 23152837592538
    TagComponent:
      Tag: camera
    TransformComponent:
      Translation: [0.150000006, 0.200000003, 2]
      EulerAngles: [0, 0, 0]
      Scale: [1, 1, 1]
    CameraComponent:
      Camera:
        ProjectionType: 1
        OrthographicSize: 10
        OrthographicNearClip: -4.5999999
        OrthographicFarClip: 18.6299992
        PerspectiveFOV: 1.04719758
        PerspectiveNearClip: 0.00999999978
        PerspectiveFarClip: 1000
      Active: true
      FixedAspectRatio: false
  - Entity: 23152837592538
    TagComponent:
      Tag: red
    TransformComponent:
      Translation: [0, 0, -0.899999976]
      EulerAngles: [0, 0, 0]
      Scale: [1, 1, 1]
    SpriteComponent:
      Colour: [1, 0, 0, 0.639215708]
  - Entity: 23152837592538
    TagComponent:
      Tag: green
    TransformComponent:
      Translation: [0.699999988, 0, -0.600000024]
      EulerAngles: [0, 0, 0]
      Scale: [1, 1, 1]
    SpriteComponent:
      Colour: [0.105882354, 0.874509811, 0.243137255, 0.623529434]
  - Entity: 23152837592538
    TagComponent:
      Tag: blue
    TransformComponent:
      Translation: [0.349999994, 0.600000024, -0.449999988]
      EulerAngles: [0, 0, 0]
      Scale: [1.64999998, 1.60000002, 1]
    SpriteComponent:
      Colour: [0.278431386, 0.164705887, 0.929411769, 0.384313732]